apiVersion: v1
kind: ConfigMap
metadata: { name: {{ .Release.Name }}-config }
data:
  NODE_ENV: production
  PORT: "3000"
{{- range $k, $v := .Values.api.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
