{{- if .Values.secrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: {{ include "rch.secretName" . }} }
spec:
  refreshInterval: 1h
  secretStoreRef: { name: {{ .Values.secrets.externalSecret.storeName }}, kind: {{ .Values.secrets.externalSecret.storeKind }} }
  target: { name: {{ include "rch.secretName" . }}, creationPolicy: Owner }
  dataFrom: [{ extract: { key: {{ .Values.secrets.externalSecret.remoteKey }} } }]
{{- end }}
